language: ruby
before_install:
  - if [[ $(ruby -v) < "ruby 2.3" ]];
    then
      gem install bundler -v "< 2";
    else
      gem update --system;
      gem install bundler;
      bundle update --bundler;
    fi

before_script: bundle exec rake compile

rvm:
# 2.0.0
- 2.1.0
- 2.1.1
# 2.1.2
# 2.1.3
# 2.1.4
- 2.1.5
- 2.1.6
- 2.1.7
- 2.1.8
- 2.2.0
- 2.2.1
- 2.2.2
- 2.2.3
- 2.2.4
- 2.3.0
- 2.3.1
- 2.3.2
- 2.3.3
- 2.4.1
- 2.4.3
- 2.5.0
- 2.5.1
- 2.5.3
- 2.6.3
